name: Linter for Dockerfile

on:
  pull_request:
    paths:
      - Dockerfile
  push:
    paths:
      - Dockerfile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install hadolint
        run: |
          curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.9.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Run hadolint on Dockerfile
        run: hadolint Dockerfile
