name: Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run hadolint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run super-linter
        uses: github/super-linter@v4