


name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build -o  ./main.go

      - name: Clean up
        run: git reset --hard
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release

        env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           GITHUB_REPOSITORY_OWNER: ${{github.repository_owner}}
           GITHUB_REPOSITORY: ${{github.repository}}
   
      - name: Build Docker image
        run:  |
           docker buildx build . -f Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}//super_calculator:${{github.ref_name}}
           echo "${{ secrets.DOCKERHUN_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
           run: docker push ${{ secrets.DOCKER_USERNAME }}/super_calculator:${{ github.ref }}
